name: gladia_example
description: Example application for Gladia Flutter SDK
version: 0.1.2
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  gladia:
    path: ../
  record: ^6.0.0
  path_provider: ^2.0.15
  permission_handler: ^12.0.0
  cupertino_icons: ^1.0.2
  args: ^2.7.0
  shared_preferences: ^2.2.2
  dio: ^5.3.2
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio_file.mp3
