name: gladia
description: A Flutter SDK for the Gladia API for audio transcription, translation, and analysis
version: 0.1.7
repository: https://github.com/xdevspo/flutter-gladia
homepage: https://gladia.io
documentation: https://docs.gladia.io
issue_tracker: https://github.com/xdevspo/flutter-gladia/issues
topics:
  - audio
  - transcription
  - api
  - translation

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.0.0
  http_parser: ^4.0.2
  meta: ^1.9.1
  json_annotation: ^4.9.0
  web_socket_channel: ^2.4.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  json_serializable: ^6.6.2
  flutter_lints: ^2.0.0
  test: ^1.24.1
  http_mock_adapter: ^0.6.1

# Flutter specific settings
flutter:
  uses-material-design: false
